// <auto-generated />
using BlotzTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlotzTask.Migrations.LabelDb
{
    [DbContext(typeof(LabelDbContext))]
    partial class LabelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlotzTask.Data.Entities.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabelId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LabelId");

                    b.ToTable("Labels");

                    b.HasData(
                        new
                        {
                            LabelId = 1,
                            Color = "Red",
                            Description = "Description for Label 1",
                            Name = "Label 1"
                        },
                        new
                        {
                            LabelId = 2,
                            Color = "Yellow",
                            Description = "Description for Label 2",
                            Name = "Label 2"
                        },
                        new
                        {
                            LabelId = 3,
                            Color = "Blue",
                            Description = "Description for Label 3",
                            Name = "Label 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
