name: Build, test and run project 

on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize
  
jobs:
    build-and-test-backend:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'

        - name: Restore dependencies
          run: dotnet restore
          working-directory: ./blotztask-api

        - name: Build the project
          run: dotnet build --configuration Release --no-restore
          working-directory: ./blotztask-api

        - name: Publish the project
          run: dotnet publish --configuration Release --output ./blotztask-api/publish --no-build
          working-directory: ./blotztask-api