name: Deploy .NET Web API Backend to Azure

on:
    push:
      paths:
        - 'blotztask-api/**'
      branches:
        - main
    pull_request:
      paths:
        - 'blotztask-api/**'
  
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'

        - name: Restore dependencies
          run: dotnet restore
          working-directory: ./blotztask-api

        - name: Build the project
          run: dotnet build --configuration Release --no-restore
          working-directory: ./blotztask-api

        - name: Publish the project
          run: dotnet publish --configuration Release --output ./blotztask-api/publish --no-build
          working-directory: ./blotztask-api

        # - name: Deploy to Azure Web App
        #   uses: azure/webapps-deploy@v2
        #   with:
        #     app-name: <your-backend-app-service-name>
        #     slot-name: 'production'
        #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        #     package: ./blotztask-api/publish